[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E","F","I","UP","N","S","B","C4","PIE","SIM","PL","RUF"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
check_untyped_defs = true
disallow_untyped_defs = false
exclude = ["tests/visual/"]

